### ISSUE TITLE
EC2Connection has no len()

### ISSUE THREAD

**Issue by jeffthomassen** [cloudability/valet#1]
Hi when testing valet out I get the following error:

![image](https://cloud.githubusercontent.com/assets/1950006/11377401/91f5f6b8-92b3-11e5-8695-162e3526d550.png)

Amazon Linux AMI release 2015.09
Python 2.7.10

--debug shows data from ec2 but it doesn't seem to getting a good list of instances to work with.

Thanks in advance.

**Comment by GylSky** [comment]
This question is old, but since the typo is still there I will just mention it here

```
scheduled_instances = ec2.get_only_instances(filters=filters)
parsed_instances = parse_instances(ec2)
```

the second line should be

```
parsed_instances = parse_instances(scheduled_instances)
```

**Comment by thecarlhall** [comment]
@jeffthomassen so sorry for not seeing this issue!
Thanks @GylSky for the proposed fix.  I've patched the code.
